# Generated by Django 2.2.16 on 2022-04-04 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20220404_1543'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredientforrecipe',
            unique_together={('ingredient', 'recipe')},
        ),
    ]
